### ISSUE TITLE
Comments Isaque

### ISSUE THREAD

**Issue by Isaquek** [nordweg/handbook#1]
- Um grande exemplo dessa forma de pensar e **inspiração** é o Netflix. Veja o culture deck no Slideshare.

- Isso **quer** dizer que cada um de nós tem um número crescente de responsabilidades. 

- Novas experiências e **aprendizados** são incluídos, reduzindo significativamente as chances de erros se repetirem.

- Alto impacto não significa fazer as coisas correndo, estar sempre com a sensação de estar atrasado, apagando **incêndios**.

- É a nossa produtividade, quando fazemos mais com menos, que banca nossos pequenos luxos que outras empresas não podem oferecer. A ** disciplina** vale a pena.

- No fim da página forma de trabalho incluir link: https://github.com/nordweg/handbook/blob/master/leitura.md

**Comment by igorgaelzer** [comment]
All fixed ;)
